# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("test.proto", :syntax => :proto3) do
    add_message "PointMessage" do
      optional :x, :int32, 1
      optional :y, :int32, 2
    end
    add_message "FeautureMessage" do
      optional :name, :string, 1
      optional :point, :message, 2, "PointMessage"
    end
    add_message "PathMessage" do
      optional :name, :string, 1
      optional :description, :string, 2
      repeated :features, :message, 3, "FeautureMessage"
    end
  end
end

PointMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PointMessage").msgclass
FeautureMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FeautureMessage").msgclass
PathMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PathMessage").msgclass
